name: Daily GEFS Forecast
permissions:
  contents: write

#here we're setting up a cron timer auromation using git hub actions
on:
  schedule:
    # 12 AM Calgary time = 6 AM UTC
    - cron: '0 06 * * *'
  workflow_dispatch:  # Manual trigger for testing

jobs:
  forecast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests numpy netCDF4 xarray cartopy shapely matplotlib pyproj cfgrib eccodes

      - name: Generate forecast data
        run: |
          python fetch_gefs_hdw.py --date $(date +%Y%m%d) --out GEFS_HDW_FCST.nc

      - name: Generate maps
        run: |
          python GeneratePlots.py

      - name: Commit and push maps
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add maps/
          git commit -m "Update forecast maps" || echo "No changes"
          git push