name: Deploy React App to GitHub Pages
permissions:
  contents: read #default least priviledge

#here we are listening to run automatically on any push to the pulling branch
#now as we added the paths it will only run build once the front end changes not the maps, 
#so we're not building and re-deploying the page every time when new pictures are created
on:
  push:
    branches: [pulling]
    #this was added to prevent extra builds
    paths:
      - 'hdwi-website/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hdwi-website
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 18

      - run: npm install
      - run: npx playwright install chromium firefox
      - run: npx playwright test


  build:
    needs: test #only running if the test job passes
    runs-on: ubunto-latest
    permissions:
      contents: write #only this jobs gets write permissions, so if more jobs are added they inherit the read not the write
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hdwi-website

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hdwi-website/build