name: Deploy React App to GitHub Pages

on:
  push:
    branches: [pulling]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hdwi-website

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hdwi-website/build